### ISSUE TITLE
COPY: Input record 1 has been rejected (Invalid float format 'NULL' for column)

### ISSUE THREAD

**Issue by lv10** [vertica/vertica-python#181]
Hi, 

When I insert one row of data to Vertica through SQLAlchemy `execute()` object I am able to pass a NULL (None) to a float column. However, when I try to do a bulk insert which hits your (_vertica_python/vertica/cursor.py:130_) `executemany()` method I get error:  _**COPY: Input record 1 has been rejected (Invalid float format 'NULL' for column)**_ . Have you guys had this issue before? If so how was it fixed? thank you.

**Comment by armaandhull** [comment]
@sitingren : I have the same issue and using @lv10 's fix on the fork works as expected. Wondering if it is possible to merge this fix into master?

**Comment by sitingren** [comment]
@armaandhull : I took a quick look and found there are 2 pull requests that may resolve this issue: #182 and #212. I think #212 is a better solution compared to #182 since it does not change API. Merging #212 is transparent to users who are already using the API. I'd like to know if #212 works for you and feel free to give me suggestions.

**Comment by armaandhull** [comment]
@sitingren : agreed that #212 is indeed the better/more transparent solution and it works for me as well :+1:
