### ISSUE TITLE
fetchmany returns only a single row

### ISSUE THREAD

**Issue by chanansh** [vertica/vertica-python#188]
Hi,
I am trying to use your driver and it works. Thanks!
Why does `fetch_many`returns a single row albeit it should return several.
I need this for faster dumping into a file (rather than line by line)

**Comment by sitingren** [comment]
If you don't pass any parameter to `fetchmany()`, the default number of rows to be fetched is `cursor.arraysize = 1`. You can specify the `size` parameter to the number of rows to fetch per call.

Here are some solutions:
* Use `fetchall()` to fetch all rows
* Call `fetchmany(size=N)` to fetch N rows
* Change `cursor.arraysize` attribute to M, then every time calling `fetchmany()` would fetch M rows

Note: The fetchmany method try to fetch as many rows as indicated by the size parameter. If this is not possible due to the specified number of rows not being available, fewer rows may be returned.
