### ISSUE TITLE
COPY STDIN: Query after failed COPY command is not executed

### ISSUE THREAD

**Issue by pcerny** [vertica/vertica-python#213]
I have an application where I trigger several COPY commands and SELECT queries using one cursor. Everything works fine till one COPY command fails with message type `messages.ErrorResponse`. After that failure, command executed by methods `cursor.execute` or `cursor.copy` do nothing.

Simple solution for this issue is to add line `self._message = message` before the line https://github.com/uber/vertica-python/blob/master/vertica_python/vertica/cursor.py#L315

When `cursor.copy` does not store read message to `cursor._message` and Exception message is returned, `cursor._message` contains `messages.ReadyForQuery` after the last successful call. So the `messages.ReadyForQuery` is read by the next call and everything is shifted by one.

Here is a test case:
```
import vertica_python
from tempfile import NamedTemporaryFile

conn_info = {'host': '127.0.0.1',
             'port': 5433,
             'user': 'vertica',
             'password': '',
             'database': 'verticadb',
             'read_timeout': 600}

fd = NamedTemporaryFile(delete=True)
file_name = fd.name
fd.write('DEMO')
fd.flush()

connection = vertica_python.connect(**conn_info)
curr = connection.cursor('dict')
try:
    with open(file_name, 'r') as f:
        curr.copy("COPY test_copy (id, name) from stdin DELIMITER ','", f)
except Exception as e:
    print(e)
    curr.execute("SELECT 1 as col")
    data = curr.fetchall()
    print("Data: {0}".format(data))
    curr.execute("SELECT 2 as col")
    data = curr.fetchall()
    print("Data: {0}".format(data))

fd.close()
connection.close()
```

**Comment by sitingren** [comment]
@pcerny Thank you for your bug report. You wrote a great bug description!

The solution is straightforward enough (Note: The url mentioned above no longer make sense after line number has changed as new PRs merged). In order to encourage external contributions, we would like to leave this bug to the community and call for help.

Here are some key points about the bug fix:
* Assign yourself as the Assignee of this issue, so that nobody else will repeat your work.
* Edit file `vertica_python/vertica/cursor.py`, under function `copy()`, find a line with content like `if isinstance(message, messages.ErrorResponse):`. Add line `self._message = message` above that line.
* Add tests in `vertica_python/tests/integration_tests/test_cursor.py`: the test case mentioned above is a good reference.
* See `CONTRIBUTING.md` for more details.

**Comment by pcerny** [comment]
@sitingren I have created PR with fix, but I cannot assign this issue to myself because I have no rights to do so.

**Comment by sitingren** [comment]
@pcerny Thanks for creating a PR! I apologize I didn't notice you don't have permissions to assign the issue.
