### ISSUE TITLE
vertica-python-0.8.2 on Python 2.7

### ISSUE THREAD

**Issue by sangram66** [vertica/vertica-python#259]
Hi,

I'm new to python, kindly bear with my naive questions.
We are using vertica-python-0.7.4 on Python 2.7.5 and it is working without any error.
Now we want to make use of backup_server_node configuration, so tried using vertica-python-0.8.2
But using this I'm getting below error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 50, in __call__
    return str(cur.fetchall()).lstrip("[").rstrip("]")
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/cursor.py", line 241, in fetchall
    return list(self.iterate())
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/cursor.py", line 222, in iterate
    row = self.fetchone()
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/cursor.py", line 208, in fetchone
    row = self.row_formatter(self._message)
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/cursor.py", line 356, in row_formatter
    return self.format_row_as_array(row_data)
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/cursor.py", line 372, in format_row_as_array
    for idx, value in enumerate(row_data.values)]
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/column.py", line 217, in convert
    return self.converter(s) if self.converter is not None else s
  File "/lib/vertica-python-0.8.2/vertica_python/vertica/column.py", line 195, in <lambda>
    ('varchar', lambda s: str(s, encoding=UTF_8, errors=unicode_error)),
TypeError: str() takes at most 1 argument (3 given)

Tried finding difference between column.py script in both version vertica-python-0.7.4 and vertica-python-0.8.2 this is where script in my system fails 

            #('varchar', lambda s: str(s, encoding=UTF_8, errors=unicode_error)),          --> vertica-python-0.8.2
            ('varchar', lambda s: str(s).encode(encoding='UTF-8',errors='unicode_error')), --> vertica-python-0.7.4

When replaced above code in vertica-python-0.8.2 (column.py), it returned result.

Could you please help me understand why we removed .encode() in vertica-python-0.8.2
Also is there a way to use vertica-python-0.8.2 without installing any python package as the servers don't have pip option or virtualenv.

Regards,
Sangram

**Comment by sitingren** [comment]
For your first question, I think your 0.7.4 source code must be modified. I checked source code history, there is no change between 0.7.4 and 0.8.2. And apparently `errors='unicode_error'` claimed unicode_error variable as a string is impossible. Can you run `from builtins import str` successfully? The `str()` is called from builtins, not the default one that python provides. If you hit "ImportError: No module named builtins", the package `future` should be installed.

For your second question, I'm not sure if I understand your question. vertica-python has a couple of dependencies, it cannot work if you don't install those dependencies. How did you install vertica-python on your server without pip and virtualenv?

**Comment by sangram66** [comment]
Thanks Siting,

I guess they are modified. 
1) for your question "Can you run `from builtins import str` successfully?" yes 

try:
    import builtins
except ImportError:
    import __builtin__ as builtins 

2)  "How did you install vertica-python on your server without pip and virtualenv?"
-- We are using the library in local instead of installing.
sys.path.append('/lib/vertica-python-0.7.4')
sys.path.append('/lib/pytz-2018.7')
sys.path.append(/lib/python-dateutil-2.7.5')

**Comment by sitingren** [comment]
Some more background...

What `lambda s: str(s, encoding=UTF_8, errors=unicode_error)` is doing is that it __decode__ a byte-string (received from server) to a unicode string (as the varchar data result send to user). Translating a unicode string into a byte-string is called __encoding__, so .encode() is not the right thing to do. I guess your data don't have special characters, so it is working.

As mentioned [here](https://www.python.org/dev/peps/pep-0414/#complaint-the-wsgi-native-strings-concept-is-an-ugly-hack), there are three different kinds of string in Python:
* text strings: handled as `unicode` in Python 2 and `str` in Python 3
* native strings: handled as `str` in both Python 2 and Python 3
* binary data: handled as `str` in Python 2 and `bytes` in Python 3

vertica-python supports both python 2.7 and python 3. In order to handle strings in py2/py3, `builtins.str()` is used. Since you use `except ImportError:`, I'm not sure if you can really `import builtins`. Please check if the return value has the correct type.
```python
type(builtins.str('abc'))
#<class 'future.types.newstr.newstr'>
```
If the type is `<type 'str'>`, you may need to "install" the `future` package as well (using sys.path.append()).

In my opinion, you are missing the `future` package. Installing this package should fix the error. If that doesn't work, I encourage you to try Python 3. Python 2 faces official end-of-life on Jan 1, 2020. It is never too early to migrate to python 3. If python 3 won't work for you, you can modify the source code as you have done in 0.7.4.
```
# Rather than
#('varchar', lambda s: str(s).encode(encoding='UTF-8',errors='unicode_error')), --> vertica-python-0.7.4

# Use .decode()
('varchar', lambda s: s.decode(encoding='UTF-8',errors=unicode_error)), 

# Or leave it as a byte-string
('varchar', None),
```

**Comment by sangram66** [comment]
Thanks a lot !!!
