### ISSUE TITLE
Iteroperation with SqlAlchemy broken in 0.9.2

### ISSUE THREAD

**Issue by roveo** [vertica/vertica-python#280]
```python
import sqlalchemy as sa

sa.create_engine('vertica+vertica_python://test:test@localhost/db')
```

Result:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in requires(self, extras)
   2731             try:
-> 2732                 deps.extend(dm[safe_extra(ext)])
   2733             except KeyError:

KeyError: 'namedparams'

During handling of the above exception, another exception occurred:

UnknownExtra                              Traceback (most recent call last)
<ipython-input-15-8fe01fb55c4d> in <module>
      1 import sqlalchemy as sa
      2 
----> 3 sa.create_engine('vertica+vertica_python://test:test@localhost/db')

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py in create_engine(*args, **kwargs)
    421     strategy = kwargs.pop("strategy", default_strategy)
    422     strategy = strategies.strategies[strategy]
--> 423     return strategy.create(*args, **kwargs)
    424 
    425 

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py in create(self, name_or_url, **kwargs)
     59         kwargs.pop("plugins", None)
     60 
---> 61         entrypoint = u._get_entrypoint()
     62         dialect_cls = entrypoint.get_dialect_cls(u)
     63 

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/url.py in _get_entrypoint(self)
    170         else:
    171             name = self.drivername.replace("+", ".")
--> 172         cls = registry.load(name)
    173         # check for legacy dialects that
    174         # would return a module with 'dialect' as the

/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py in load(self, name)
    220     def load(self, name):
    221         if name in self.impls:
--> 222             return self.impls[name]()
    223 
    224         if self.auto_fn:

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in load(self, require, *args, **kwargs)
   2431             )
   2432         if require:
-> 2433             self.require(*args, **kwargs)
   2434         return self.resolve()
   2435 

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, env, installer)
   2454         # requirements for that extra are purely optional and skip over them.
   2455         reqs = self.dist.requires(self.extras)
-> 2456         items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2457         list(map(working_set.add, items))
   2458 

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    792 
    793             # push the new requirements onto the stack
--> 794             new_requirements = dist.requires(req.extras)[::-1]
    795             requirements.extend(new_requirements)
    796 

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in requires(self, extras)
   2733             except KeyError:
   2734                 raise UnknownExtra(
-> 2735                     "%s has no such extra feature %r" % (self, ext)
   2736                 )
   2737         return deps

UnknownExtra: vertica-python 0.9.2 has no such extra feature 'namedparams'
```

**Comment by roveo** [comment]
Looks like the change was made in #276 
I'm using [LocusEnergy/sqlalchemy-vertica-python](https://github.com/LocusEnergy/sqlalchemy-vertica-python) for connecting from Jupyter and it has [namedparams] in the requirements.

**Comment by sitingren** [comment]
Please report this issue to LocusEnergy/sqlalchemy-vertica-python.

**Comment by pachewise** [comment]
Hi @sitingren - sqlalchemy-vertica-python doesn't have any support right now. One of their former contributors mentioned that they asked if vertica could take over support here, but that there wasn't any bandwidth for that (see convo at https://github.com/LocusEnergy/sqlalchemy-vertica-python/issues/35). We use both vertica_python and the sqlalchemy-vertica-python adapter at my company, but given the lack of updates on the latter, I see the following options moving forward:

1. vertica takes over the sqlalchemy-vertica-python repo, either by (a) transferring ownership (like you did for this repo) or (b) forking it. This will require release management on your part, but I think users of this library can contribute most of the improvements (and you would mostly be reviewing/approving and uploading to PyPI). 
2. One of the downstream users of the library either (a) transfers ownership or  (b) forks the library and creates a new PyPI entry.

Less interested in (2) because it may fall into the same issue - all the maintainers leave the company and it falls behind on updates. Granted, I may end up doing this for our company, anyway, but it'd be a shame if we end up with a bunch of disparate copies of sqlalchemy-vertica-python (I think there are 2-3 already) because we don't have a central "official" library (ideally, under the Vertica org on GH).

**Comment by sitingren** [comment]
According to conversations at 
https://github.com/LocusEnergy/sqlalchemy-vertica-python/pull/37#issuecomment-589158302,
https://github.com/bluelabsio/sqlalchemy-vertica-python is the new fork and continues to publish to https://pypi.org/project/sqlalchemy-vertica-python/. 

@lemeryfertitta @vinceatbluelabs We really appreciate your great efforts to make this project continue!
