### ISSUE TITLE
Connection pooling support

### ISSUE THREAD

**Issue by bryanherger** [vertica/vertica-python#290]
Does this driver support connection pooling, either natively or via another package?

If not, is there a plan to implement connection pooling in this driver?

**Comment by tomwall** [comment]
No, vertica-python does not implement connection pooling. Doing so is not a priority at this point in time. 

Connection pooling is not as beneficial for Vertica as it is for more traditional OLTP databases, where the latency of establishing a connection could constitute a majority of the overall runtime of the query or request. Vertica workloads usually consist of a relatively small volume of large queries, where a few 10's of milliseconds to open a connection doesn't contribute much to the overall runtime. For very large database catalogs and for the more complex authentication processes you might want to worry about the connection time, but usually it isn't a concern.

Pooling adds complexity and new failure patterns your application will have to worry about. If you have long lived connections idle in the pool you have to worry about cleaning them up, or with aggressive firewalls/TCP timeouts cleaning them up when you didn't intend to. There can be security concerns because pools recycle sessions without necessarily re-initializing them via reset_session() or some other mechanism. Some memory allocations in vertica are scoped to the lifetime of a session, so very long lived sessions can sometimes accrue more memory than a fresh session would require. Normally those allocations are inconsequential, and if they aren't it's the sign of a vertica bug. We'd happily fix such a bug if/when we find them of course, but you can avoid that class of problems entirely if you don't need long sessions that pooling encourages.

So given all that you have to ask yourself, is it worth the trouble & complexity to use connection pooling? In my experience it is frequently assumed to be necessary when in practice it often isn't. If you don't have a known latency/performance problem or other good reason, I wouldn't bother using one. 

There do appear to be connection pools in python tools that may consume this client, like SQLAlchemy or Django. I can't vouch for them since I haven't tried them personally but if you really need pooling those may help.
