### ISSUE TITLE
Cursor.close() tries to close prepared statement even if doesn't exist

### ISSUE THREAD

**Issue by ddpimkin** [vertica/vertica-python#299]
Hi!

Current behaviour on close cursor:
```
def close(self):
    self._logger.info('Close the cursor')
    if not self.closed():
        self._close_prepared_statement()
    self._closed = True
```
Cursor object tries to close prepared statement even if doesn't exist.
But when there is no prepared statement, this manipulation leads to unexpected behavior: it makes backend think that `transaction_status` is `T` (in_transaction) even if it's not the true.
Ultimately, this prevents to make automatic commit (`self.commit()`) when exiting from `Connection` context manager here:
```
def __exit__(self, type_, value, traceback):
    try:
        # if there's no outstanding transaction, we can simply close the connection
        if self.transaction_status in (None, 'in_transaction'):
            return

        if type_ is not None:
            self.rollback()
        else:
            self.commit()
    finally:
        self.close()
```

I know that I can (and may be should) do commit manually, but when I use Connection context manager I want this to happen automatically.

Expected behaviour: close prepared statement only if exists:
```
def close(self):
    self._logger.info('Close the cursor')
    if not self.closed() and self.prepared_sql:
        self._close_prepared_statement()
    self._closed = True
```

How to reproduce:
```
with vertica_python.connect(**vcreds) as conn:
    cur = conn.cursor()
    cur.execute('drop table if exists tmp_test_cursor')
    cur.execute('create table tmp_test_cursor (a int)')
    cur.execute('insert into tmp_test_cursor values (1)')
    cur.close()

with vertica_python.connect(**vcreds) as conn:
    cur = conn.cursor()
    cur.execute('select * from tmp_test_cursor')
    print(cur.fetchall())
```

**Comment by sitingren** [comment]
@ddpimkin Thanks for reporting this. I think this is a problem about updating "transaction_status" lazily, not close prepared statement.

After you run `cur.execute('insert into tmp_test_cursor values (1)')`, `transaction_status` actually is `T` (in_transaction), but `__exit__()` still get the old value `no_transaction`. So that's why you see a commit after you modifying `cursor.close()`. If you execute 2 or more insert statements, you'll see your fix won't work.

So vertica-python is doing the right thing but has a wrong implementation. It is required to do commit manually, you should not rely on `__exit__()` to make automatic commit.

**Comment by ddpimkin** [comment]
Thanks for your reply!
You are right. I looked at messages from backend again and found that after my insert statement Vertica responded with `T`, exactly like you said.
I will do commit manually.
