### ISSUE TITLE
Request for bringing up local vertica container automatically for integration tests

### ISSUE THREAD

**Issue by ranjanp75** [vertica/vertica-python#304]
Currently, the integration tests require the developers to manually install the vertica container for running the integration tests. However, installing and bringing up vertica can be a very daunting task . I would like to propose automating the process through the following steps.

1. Install docker on the machine 
2. Run the vertica container  https://github.com/jbfavre/docker-vertica
3. Run the integration tests 
4. Stop the vertica container

**Comment by ranjanp75** [comment]
@sitingren I would like to work on this enhancement if it sounds good for running integration tests on local vertica

**Comment by sitingren** [comment]
@ranjanp75 Thanks for providing your opinion! Can you tell me which file(s) are you going to modify/add to implement your proposed process?

**Comment by ranjanp75** [comment]
I have a method to achieve this. 
In the tox.ini file under "commands" shell commands to achieve the above tasks can be written before and after the nosetests command

**Comment by sitingren** [comment]
@ranjanp Here's some of my thoughts:
1. Do you have mechanisms to make it be optional? Not every developer needs a Vertica docker container.
2.  Spining up a vertica container is time-consuming. Is it efficient to re-create a container every time you restart `tox`? To me, this is a one-time setup locally and I can change codes and run tox tests for multiple times.
3. The `tox.ini` in the repo is mainly used by our CI tool (`.travis.yml`), and used as an example for developers as well. Any commit merges to `tox.ini` should not break Travis CI and be general to all developers. Otherwise, it is better to mention your customization in `CONTRIBUTING.md`.

Feel free to create a PR when you think your solution is solid and general.

**Comment by ranjanp75** [comment]
@sitingren thanks for the information. I will work on it if I get a way to do it . Are there any priority features I can work on ? Thanks

**Comment by sitingren** [comment]
@ranjanp75 There are no feature that has higher priority than others. You can look at the open issue list and work on anything that you are interested in.

**Comment by sitingren** [comment]
Close this issue for now. Please reopen when you have new updates.
