### ISSUE TITLE
Retrieve ConnectionError message

### ISSUE THREAD

**Issue by zlordaccount** [vertica/vertica-python#313]
Hey Community,

I'm working with Vertica_python 0.9.5 and am hoping to get the message stored in the Connection Error for use with some specific messaging out to the end user.

Is this possible?

Attempting to use the vp.errors.ConnectionError(message.error_message()) code which is raised in pycharm when there is an error it fails out because message doesn't exist evidently.

Any assistance appreciated

**Comment by sitingren** [comment]
@zlordaccount Can you give me an example? I'm not sure if I understand your question.

If message is an instance of NoticeResponse or ErrorResponse, `message.error_message()` would return all details as a string. `message.sqlstate`, `message.severity`, `message.error_code`, etc. are attributes of specific detail. You can find those attribute names at [here](https://github.com/vertica/vertica-python/blob/b5f1e44f16f18ff476071be7aa05355fc9e913b5/vertica_python/vertica/messages/backend_messages/notice_response.py#L42).

**Comment by DerrickRice** [comment]
Related issues #312 #314

**Comment by DerrickRice** [comment]
With https://github.com/vertica/vertica-python/pull/328, getting the error message from a QueryError is simple.

ConnectionErrors never had an internal error or notice response, but they did lack the original error text. That's been fixed with https://github.com/vertica/vertica-python/pull/317

I suspect your question is answered with these changes.

**Comment by sitingren** [comment]
@zlordaccount Re-open this issue if you have further questions.
