### ISSUE TITLE
future is a python core module 

### ISSUE THREAD

**Issue by leonidlee** [vertica/vertica-python#330]
Future is listed in dependency. 
But we can find that it is a python core module.
[python documentation](https://docs.python.org/2/search.html?q=__future__)
and:
```
>>> help('modules')

Please wait a moment while I gather a list of all available modules...

__future__    
...
```
So there is no need to mention it in setup.py and requirements.txt.

The reason I opened this issue is a number of security issues in the project future that is located on https://github.com/PythonCharmers/python-future (source code for future module from pypi).

I used bandit module and owasp dependency check to scan for security issues.

**Comment by sitingren** [comment]
Hi @leonidlee Thanks for your suggestion.

The `builtins` module is used in vertica-python:
https://github.com/vertica/vertica-python/search?q=builtins&unscoped_q=builtins

My experience is that if I don't install `future` in python2.7, when using vertica-python I can get the [error](https://stackoverflow.com/questions/27495752/no-module-named-builtins): `ImportError: No module named builtins`. Therefore, `future` module needs to be mentioned in setup.py and requirements.txt.

I propose to remove `builtins` usage in vertica-python, so that you can remove `future` in setup.py and requirements.txt. Certainly there will be behavior change (probably only affect python 2.7 behavior). 

What do you think?

**Comment by leonidlee** [comment]
Hi @sitingren I checked: 
Python 2.7.5 does not contain builtins
Python 2.7.16 contains.
But Centos 7 is bundled with Python 2.7.5.

According to https://www.python.org/doc/sunset-python-2/ python 2 will retire in 1 month.
So it would be good to remove python 2 support at all.
What do you think?

**Comment by sitingren** [comment]
@leonidlee Yes, that's reasonable. But right now I don't have cycle to evaluate the behavior change for Python2 and finish this task. We still have to take care of python2 users in these two months. I'd rather make this change after Jan 1, 2020 if nobody do this for me.
