### ISSUE TITLE
Copy query gives error while reading CSV file from inMemroy Object

### ISSUE THREAD

**Issue by UsmanShabbir97** [vertica/vertica-python#345]
When I have upgraded version from 0.6.14 to 0.10.0. Copy command giving error while loading a CSV file from InMemory Object. 

> No valid type of data <class 'django.core.files.uploadedfile.InMemoryUploadedFile'>

**Comment by sitingren** [comment]
Thanks for reporting this issue. This is a regression. In 0.6.14, all objects with the 'read' attribute are acceptable by `Cursor.copy`. Now, only objects with their types in the whitelist is valid.

The 'django.core.files.uploadedfile.InMemoryUploadedFile' class is a wrapper around a Python file object with some Django-specific additions. You got that error because it is not in the whitelist.

I'll create a fix to restore the ability of `Cursor.copy` to read from objects that have a 'read' method.

**Comment by UsmanShabbir97** [comment]
Thank you @sitingren for the update. can i get this fix in this release or this will be a part of next release?

**Comment by sitingren** [comment]
This fix will be a part of next release.

**Comment by sitingren** [comment]
@UsmanShabbir97 Now you can get the fix in version 0.10.1.

**Comment by UsmanShabbir97** [comment]
@sitingren Thanks for the update.
