### ISSUE TITLE
Column based wire format

### ISSUE THREAD

**Issue by alippai** [vertica/vertica-python#358]
Is it possible to create Pandas or Arrow tables/dataframes directly?
Does Vertica have to serialize the result into rows and then the vertica-python client back to a column based representation instead of sending batches of columns in the response?

**Comment by alippai** [comment]
Eg. there is an export to parquet feature, but I don't think it can stream the output file over vertica-python or vsql - or is this possible?

**Comment by sitingren** [comment]
> Is it possible to create Pandas or Arrow tables/dataframes directly?

No. vertica-python does not provide those result types directly, you need a wrapper to convert the result format.

vertica-python is compliant with [Python DB-API](https://www.python.org/dev/peps/pep-0249/), so it is possible to use query wrappers provided by *pandas*, for example 
```python
import pandas as pd
import vertica_python

with vertica_python.connect(**conn_info) as conn:
    pandas_data = pd.read_sql("select * from mytable", con=conn)
    print(pandas_data.head())
```
Let me know if your question is answered.

**Comment by alippai** [comment]
Python DB-API doesn't define columns and record batches, it iterates over rows.
On the other hand Pandas, Arrow, numpy and others keep values from one column close, they don't allocate per row, but they try to keep values from one column close and allocating in batches, keeping the col width aligned. This is what Vertica server does internally too, hence this question.
Based on your answer I assume the protocol doesn't support serialization as A1, A2, A3, B1, B2, B3, C1, C2, C3 only A1, B1, C1, A2, B2, C2, A3, B3, C3 (where A,B,C are columns, 1,2,3 are row numbers)

**Comment by sitingren** [comment]
Vertica server is using columnar storage, but the client-server protocol does not serialize query results into columns.

@tomwall may have more insights into this question.

**Comment by tomwall** [comment]
Vertica's client protocol is row-oriented because most database API's, python dbapi included, are row oriented. Most database API's also expect to interact with a single node, which is not suitable to big data migration tasks which demand lots of parallelism across many machines.

Vertica's internal node-to-node communications that happen in service of a given query do have a columnar protocol, but it was not designed to be consumed outside the core database engine. I don't know of a robust and well-adopted standard to consume such information. Apache arrow is close, but it alone does not seem sufficient because it doesn't really say how to orchestrate the process of getting two distributed systems with similar columnar memory layouts to communicate. 

Vertica does have various ways to export data in columnar formats like parquet, but today you do that through SQL commands that write data in columnar formats to some external stage system like hdfs or s3, not through a custom wire protocol or API. Most other systems know how to consume from there, but it does add an extra step and require persistence. That's often not as bad as it sounds, because if you persist things you have an opportunity to checkpoint and retry on partial failure without having to restart the whole processing pipeline.

For pandas for example, you can probably run a Vertica export to parquet on s3, and then consume it via https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html

**Comment by alippai** [comment]
@tomwall @sitingren turbodbc is up to ~5x faster for medium/large resultsets. It directly creates pyarrow tables. I think this is their selling point. If you could make something similar on wire protocol level it'd be superior definitely. Turbodbc still uses odbc protocol which you don't really need for Vertica server -> PyArrow export, yours would be simpler and faster.

**Comment by alippai** [comment]
@wesm does any of the databases support Arrow/Parquet "over-the-wire" now? Would it make sense?

**Comment by wesm** [comment]
I think both BigQuery and Snowflake support Arrow over-the-wire now, and I heard rumbling that Apache Kudu was working on this, too.
