### ISSUE TITLE
Parametized queries & tuple issue

### ISSUE THREAD

**Issue by adrean** [vertica/vertica-python#368]
Hello!

We ran into some issues with the last release of the package.
I've seen that there were some changes for parametized queries that break some of our work.
It seems that we now can't execute queries with tuple parameters.

For instance, this dumb example
```
with conn.cursor() as curs:
    curs.execute("SELECT %s in %s", (1, (1,2,3)))
    for row in curs.iterate():
        print(row)
```
was running successfully until `0.10.2`, but not working with `0.10.3`. We get the following issue: `TypeError: Cannot convert <class 'tuple'> type object to an SQL string`

Sorry if this is an expected behavior of the last release :)
Have a nice day!

**Comment by sitingren** [comment]
Hi @adrean, thank you for your feedback. This is an expected behavior of `0.10.3` as it would prevent SQL injection attacks. `tuple` is a type that we haven't provided a default adapter.

You can register a new adapter for `tuple` type via the `Cursor.register_sql_literal_adapter()` function. For your example above, if ALL elements in a tuple are integers:
```python
def adapt_tuple(tpl):
    return str(tpl)
curs.register_sql_literal_adapter(tuple, adapt_tuple)
curs.execute("SELECT %s in %s", (1, (1,2,3)))
```
However, if any element in a tuple needs to be escaped (e.g. single quote in string), the adapter will be something like this:
```python
def adapt_tuple(tpl):
    result = []
    for i in tpl:
        result.append(cur.object_to_sql_literal(i))
    result = '(' + ','.join(result) + ')'
    return result
cur.register_sql_literal_adapter(tuple, adapt_tuple)
cur.execute("SELECT %s in %s", ("A", ("A","B's","C")))  # SELECT 'A' in ('A','B''s','C')
```

We plan to provide the default adapter for `tuple` in next release. Please use this workaround at this time. Thank you!

**Comment by adrean** [comment]
Hi @sitingren , thanks for the quick reply, we'll use your workaround, or stick with the previous version, not sure yet.
Looking forward having this enhancement done 👍

**Comment by sitingren** [comment]
@adrean Version 0.10.4 includes this enhancement.
