### ISSUE TITLE
Parallel COPY support and unclosed stream support

### ISSUE THREAD

**Issue by maiorBoltach** [vertica/vertica-python#378]
Good afternoon.
1. Is it possible to execute multiple COPY in parallel using vertical-python in one transaction? (maybe in different threads?)
2. Is there a counterpart to [VerticaCopyStream ](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/ConnectingToVertica/ClientJDBC/UsingVerticaCopyStream.htm) in vertica-python? (maybe somehow through io.StringIO?) I mean the ability to execute copy until it wouldn't be closed

Thank you for the attention

**Comment by sitingren** [comment]
> 1. Is it possible to execute multiple COPY in parallel using vertical-python in one transaction? (maybe in different threads?)

I'm not sure about the answer. There aren't any multithreading test. You can have a try.

> 2. Is there a counterpart to VerticaCopyStream in vertica-python? (maybe somehow through io.StringIO?) I mean the ability to execute copy until it wouldn't be closed

No. Currently, `cursor.copy()` would stop loading data when `data_stream.read()` returns an empty string (when EOF is encountered) rather than data stream is closed.
https://github.com/vertica/vertica-python/blob/dfe7f531f08459f255ddf3154c01227ee1dfce6d/vertica_python/vertica/cursor.py#L408-L418

**Comment by tomwall** [comment]
Re: question 1 -- a vertica session only ever runs one command at at time. There are never parallel queries or copy statements going on in the same session/transaction. This is a pretty fundamental invariant that has broad design implications across the product. 

That's not to say there's no parallelism. Vertica will process things in parallel, both within a node and across nodes, whenever possible. But that kind of parallelism is usually an implementation detail of the command you are running, and some commands/loading mechanisms offer more opportunities for parallelism than others.

One design implication of the one active command per session invariant is in the client protocol -- all command, result & COPY STDIN I/O for a particular client session happens over a single TCP connection to a single initiator node. 

Given that design, adding parallelism at the vertica-python API level won't help much since it all gets serialized and sent over that one TCP connection. You may be able to get more load throughput with more sessions/vertica-python connections on different threads, but each one operates independently in different transactions. Python's global interpreter lock might also get in the way.

COPY STDIN is nice and simple, but you pay for that simplicity in scalability of throughput. The STDIN data gets sent from the client to the initiator node over the session's single TCP connection, and from there the initiator node parses & distributed records to all the other nodes. 

This is often good enough, especially for small clusters, but as your database grows, so does the need for more advanced load methods. You usually can't keep a cluster's worth of vertica nodes busy parsing the data if it is all coming from a single TCP connection on one initiator node. You can add more parallel sessions doing COPY STDINs to different initiators, but at some point you will run into your resource pool's configured limits and then those parallel requests from different sessions will start executing serially too.

Instead, you may want to leverage one of the existing parallel loading mechanisms, server-side files, kafka, hdfs, s3, etc., or write your own source with UDL's. With these kinds of loads, the client session's TCP chatter is solely for command/control flow, and not the source of data like it is with COPY STDIN. With these loads, the initiator instructs each node to reach out to the source for data in parallel, all during the course of a single COPY statement. It is more work to orchestrate such a load, but once you do it can scale with the number of Vertica nodes without having to do lots of adjustments to your client logic.

So in the end, the right approach depends on your size, throughput and use case requirements. It is probably best to start with a COPY STDIN and cursor.copy(), benchmark it and tune accordingly. The interface is a little different, but it achieves the same effect that VerticaCopyStream does. You should be able to pass a StringIO or anything with the right read() signature that Siting pointed out above, and if you want to write to it in parallel or do anything else, you may be able to implement that in your application logic and/or in the stream-like object you pass in.
