### ISSUE TITLE
TypeError: Cannot convert <class 'sqlalchemy.sql.elements.ColumnClause'> type object to an SQL string

### ISSUE THREAD

**Issue by AresEkb** [vertica/vertica-python#385]
Hi

I use `vertica-python` with SQLAlchemy. I wrap some of the query parameters using `sqlalchemy.sql.column` or `sqlalchemy.text` and get the TypeError.

It seems that it's not easy to call `Cursor.register_sql_literal_adapter()` to register these SQLAlchemy types. So I removed the exception raising for unknown types. Here is a commit into my fork: https://github.com/AresEkb/vertica-python/commit/1c288df806fb1a7ed3985ac8b810d57eef9f9aa1

Could you please fix it the right way in your repository?

**Comment by sitingren** [comment]
Hi @AresEkb 

These types are not general type for our users, supporting them in `vertica-python` will add dependency for sqlalchemy, which doesn't make sense. So we cannot fix it in this repository.

I know there are no way to access to `Cursor.register_sql_literal_adapter()` from SQLAlechemy core API, but from SQLAlechemy connection you can try methods like this:
```python
from sqlalchemy import *
e = create_engine(".......")
conn = e.connect()
cur = conn.cursor()
cur.register_sql_literal_adapter(...)
```

**Comment by AresEkb** [comment]
I don't mean that the direct support for these types should be added to `vertica-python`. I mean that you could just remove exception raising for unknown types. Maybe it can be controlled by a configuration property to raise or not to raise the exception.

SQLAlchemy implements the `@compiles` decorator. Please see https://docs.sqlalchemy.org/en/13/core/compiler.html

For example I can define the following `MyColumn` datatype:

```
class MyColumn(ColumnClause):
    pass

@compiles(MyColumn)
def compile_mycolumn(element, compiler, **kw):
    return '"%s"' % element.name
```

And then I can wrap a column name using this class `MyColumn('some_column_name')` and set this value as a parameter for query. For example the query is `SELECT :col_name FROM some_table` and `:param=MyColumn('some_column_name')`. The final query will be `SELECT "some_column_name" FROM some_table`.

You don't need to add any special support to let it work. It works just fine if the function `Cursor.object_to_string()` doesn't throw the exception for unknown types. Just let such a values to be casted to a string and that's all.

**Comment by sitingren** [comment]
As mentioned in README, parameters are not used for merging table or field names:
> Prerequisites: Only SQL literals (i.e. query values) should be bound via these methods: they shouldn’t be used to merge table or field names to the query (vertica-python will try quoting the table name as a string value, generating invalid SQL as it is actually a SQL Identifier). If you need to generate dynamically SQL queries (for instance choosing dynamically a table name) you have to construct the full query yourself.

#362 is a similar question. And here is the documentation for [SQL Identifier](https://www.vertica.com/docs/10.0.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Identifiers.htm?tocpath=SQL%20Reference%20Manual%7CSQL%20Language%20Elements%7C_____2) and [SQL literals](https://www.vertica.com/docs/10.0.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Literals/Literals.htm?tocpath=SQL%20Reference%20Manual%7CSQL%20Language%20Elements%7CLiterals%7C_____0).

The most important purpose of passing data to fill a query placeholders and let vertica-python perform the correct conversion rather than binding parameters at user's side is preventing SQL injections. With this security concern, vertica-python must raise exceptions for unknown types. If you don't care about security, you can construct the full query yourself. But I don’t think it is reasonable to add a configuration property to make vertica-python more unsafe.
