### ISSUE TITLE
Inconsistent manual and "with-statement" connection close behaviour

### ISSUE THREAD

**Issue by hhromic** [vertica/vertica-python#387]
In the README of the repository, it is implied that closing connections manually or using a `with` statement is equivalent:

```python
# simple connection, with manual close
connection = vertica_python.connect(**conn_info)
# do things
connection.close()

# using with for auto connection closing after usage
with vertica_python.connect(**conn_info) as connection:
    # do things
```

However, the close behaviour between the two approaches is not equivalent.

When manually calling the `close()` method of the connection, this is executed:
https://github.com/vertica/vertica-python/blob/d98179f6c9268ff8131a77b75460b56319cd80ed/vertica_python/vertica/connection.py#L337-L342

However when using a `with` statement, the `__exit__()` hook does extra work than just closing:
https://github.com/vertica/vertica-python/blob/d98179f6c9268ff8131a77b75460b56319cd80ed/vertica_python/vertica/connection.py#L318-L332

I believe that both approaches should have the exact same connection closing behaviour. In this case maybe a `flush()` method should be implemented containing the transaction flushing code in `__exit__()` and then the correct manual approach should be:
```python
# simple connection, with manual close
connection = vertica_python.connect(**conn_info)
# do things
connection.flush()
connection.close()
```

Similarly, the `__exit__()` hook can then be simplified to something like this to be consistent:
```python
def __exit__(self, type_, value, traceback):
    self.flush()
    self.close()
```

**Comment by sitingren** [comment]
@hhromic Thanks for your report. Since [DB-API](https://www.python.org/dev/peps/pep-0249/) doesn't define with-statement closing behavior, different database python clients implement this part differently. After discussion, we will do the following changes for _vertica-python_ to make closing behavior consistent:

- with-statement close will only call the close() method of the connection, and do nothing for the transaction. In other words, it will not commit/rollback for the user automatically upon exit. connection.close() performs the necessary task of closing a session. User will use the AUTOCOMMIT setting to control their transactions, this will prevent an unexpected commit upon with-statement exit when AUTOCOMMIT is set to off. 

- Update README and suggest the right way to use connection.close() is to put it into `try: ... finally: conn.close()` format.

- Currently, user have to run sql "set session autocommit to {on|off}" to change the AUTOCOMMIT setting. We plan to provide better APIs (connection option and attribute getter&setter) for user to switch the AUTOCOMMIT setting.

Let me know if you have any suggestions, thanks!

**Comment by hhromic** [comment]
Hi @sitingren , sorry for the late reply.
I think your proposal is pretty good! Thanks for taking care of this!
